
class Test7
{
  public static void main(String args[])
  {
	 System.out.println("box \u25A0");
	 System.out.println("**************************");
	 System.out.println("**************************");
	 System.out.println("**************************");
	 System.out.println("**************************");
	 
	 System.out.println("oval \u2b56");
	 System.out.println("arrow \u2192");
	 System.out.println("diamond \u22c4");
  }

}